export const VIDEO_ADD_REQUEST = "VIDEO_ADD_REQUEST";
export const VIDEO_ADD_SUCCESS = "VIDEO_ADD_SUCCESS";
export const VIDEO_ADD_FAIL = "VIDEO_ADD_FAIL";
export const VIDEO_DELETE = "VIDEO_DELETE";
export const ALL_VIDEO_DELETE = "ALL_VIDEO_DELETE";
export const ADD_VIDEO_TO_FAVORITE = "ADD_VIDEO_TO_FAVORITE";

export const FILTER_VIDEO = "FILTER_VIDEO";
export const FILTER_VIDEO_ALL = "FILTER_VIDEO_ALL";

export const SORT_VIDEO_BY_LATEST = "SORT_VIDEO_BY_LATEST";
export const SORT_VIDEO_BY_THE_OLDEST = "SORT_VIDEO_BY_THE_OLDEST";